### ISSUE TITLE
Bug：全屏程序关闭后不会重新变成亚克力效果

### ISSUE THREAD

**Issue by StandAlong** [haruyukilxz/deepin-topbar#79]
1.窗口全屏之后topbar变黑，此时直接关闭窗口topbar不会恢复；
2.Deepin 15.6的桌面上放置文件依然会有半截卡在topbar里。
望有空闲修复一下然后部署在源上，谢谢。

**Comment by aiamuzz** [comment]
@StandAlong ... do you mean something found on [this](https://github.com/haruyukilxz/deepin-topbar/issues/68) thread ?

**Comment by haruyukilxz** [comment]
I am busy with deepin 15.7. These problems will be dealt with later.
