### ISSUE TITLE
Can't install, source is unreachable (502 BadGateway)

### ISSUE THREAD

**Issue by FCatinella** [haruyukilxz/deepin-topbar#80]
Ign:2 https://packages.mkacg.com panda InRelease
Err:3 https://packages.mkacg.com panda Release
  502  Bad Gateway
Lettura elenco dei pacchetti... Fatto
E: The repository 'https://packages.mkacg.com panda Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Looks like your PPA is offline or at least unreachable

**Comment by haruyukilxz** [comment]
problems have now been sorted.
